### ISSUE TITLE
Tried to register two views with the same name RNSVGPath

### ISSUE THREAD

**Issue by tejas31218** [codesinghanoop/react-native-d3multiline-chart#11] opened 2019-03-25 06:11 UTC
**package.json**
```
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "^32.0.0",
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
    "react-native-d3multiline-chart": "^1.0.18",
    "react-native-svg": "^5.4.1",
    "svg-path-properties": "^0.4.8"
  },
  "devDependencies": {
    "babel-preset-expo": "^5.0.0"
  },
  "private": true
}

```

**Comment by codesinghanoop** [comment] 2019-03-25 16:46
@tejas31218 what is the issue you are facing can you please describe briefly, please share error logs and your code snippet. thanks

**Comment by tejas31218** [comment] 2019-03-26 05:44
When I run my code I get an error saying **Tried to register two views with the same name RNSVGPath**

```
import React from "react";
import { StyleSheet, Text, View, Dimensions } from "react-native";
import { MultiLineChart } from "react-native-d3multiline-chart";

export default class App extends React.Component {
  data = [
    [
      {
        y: "202",
        x: 2000
      },
      {
        y: "215",
        x: 2001
      },
      {
        y: "179",
        x: 2002
      },
      {
        y: "199",
        x: 2003
      },
      {
        y: "134",
        x: 2003
      },
      {
        y: "176",
        x: 2010
      }
    ],
    [
      {
        y: "152",
        x: 2000
      },
      {
        y: "189",
        x: 2002
      },
      {
        y: "179",
        x: 2004
      },
      {
        y: "199",
        x: 2006
      },
      {
        y: "134",
        x: 2008
      },
      {
        y: "176",
        x: 2010
      }
    ]
  ];

  leftAxisData = [134, 144, 154, 164, 174, 184, 194, 204, 215];
  bottomAxisData = [2000, 2002, 2004, 2006, 2008, 2010];
  legendColor = ["#00b7d4", "red"];
  legendText = ["sales", "year"];
  
  minX = 2000;
  maxX = 2010;
  minY = 134;
  maxY = 215;

  Color = ["#00b7d4", "red"];

  render() {
    return (
      <View style={styles.container}>
        <MultiLineChart
          data={data}
          leftAxisData={leftAxisData}
          bottomAxisData={bottomAxisData}
          legendColor={legendColor}
          legendText={legendText}
          minX={minX}
          maxX={maxX}
          minY={minY}
          maxY={maxY}
          scatterPlotEnable={false}
          dataPointsVisible={true}
          Color={Color}
        />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center"
  }
});
```
![Simulator Screen Shot - iPhone Xʀ - 2019-03-26 at 10 52 30 (2)](https://user-images.githubusercontent.com/48902285/54973852-bd985f80-4fb7-11e9-8e22-db6978a18130.png)

**Comment by codesinghanoop** [comment] 2019-03-26 06:35
According to me the issue is there are two react-native-svg library versions in your project. One is inside the expo sdk and one which you integrated as a peer dependency of this library. To resolve this issue i think i have to upgrade this library to support expo. If you like to go ahead and resolve this then you can submit a PR. Let me know if you have any other issue. closing for now. Thanks.

**Closed as completed by codesinghanoop** 2019-03-26 06:35 UTC
